# **Chapter No.6**
## Numpy and its use

# Arrays

In [2]:
import numpy as np
a= np.array([5,5,5,5,5,5])
a

array([5, 5, 5, 5, 5, 5])

In [3]:
type(a)

numpy.ndarray

In [5]:
b=np.array([[2,2,2,2,2],[2,2,2,2,2],[2,2,2,2,2],[2,2,2,2,2]])
b

array([[2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2]])

In [168]:
b.ndim

2

In [9]:
# length of array
len (a)

6

In [8]:
len (b)

4

In [10]:
b [2]

array([2, 2, 2, 2, 2])

In [11]:
a[0]

5

In [12]:
type(b)

numpy.ndarray

In [14]:
c= np.array([1,2,3,4,5,6,7,8,9])
c

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
d=np.zeros(5)
d

array([0., 0., 0., 0., 0.])

In [22]:
e=np.ones(5)
e

array([1., 1., 1., 1., 1.])

In [27]:
f=np.empty(5)
f

array([1., 1., 1., 1., 1.])

In [28]:
ag=np.array(["saif","saiqa","mom","dad","azam"])
ag

array(['saif', 'saiqa', 'mom', 'dad', 'azam'], dtype='<U5')

# How to create an array

In [29]:
# create array with rang of elements
af=np.arange(10)
af
#Note: last digit is exclusive in python thats why last digit (10) is not mentioned in the aray. You can check 0 is mentioned in the answer

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [32]:
#create array with specific range of elements
ah=np.arange(2,200)
ah

array([  2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,  14,
        15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,  27,
        28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,  40,
        41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,  53,
        54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,  66,
        67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,  79,
        80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,  92,
        93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103, 104, 105,
       106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118,
       119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131,
       132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144,
       145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157,
       158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170,
       171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 18

In [34]:
ahi=np.arange(15,100)
ahi

array([15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
       32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
       49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65,
       66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82,
       83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [35]:
# array with a specific interval for example, array from 2-20 , but with interval of 2. lets have a look on example:
ag=np.arange(2,20,2)
ag

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [38]:
#Linerly spcaed array
ah=np.linspace(0,1000,num=11)
ah

array([   0.,  100.,  200.,  300.,  400.,  500.,  600.,  700.,  800.,
        900., 1000.])

In [40]:
# specific data type array
ai=np.ones(10,dtype=np.int8)
ai

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int8)

In [44]:
aj=np.ones(10,dtype=np.int64)
aj

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

# Two dimensional array

In [45]:
t1= np.zeros((3,4))
t1

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [47]:
t2=np.ones((4,5))
t2

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [48]:
t3=np.empty((4,5))
t3

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

# Three dimensional array

In [129]:
#making and reshing 3D array
a1=np.arange(24).reshape(2,3,4)
a1

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [135]:
a2=np.arange(60).reshape(5,3,4)
a2

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]],

       [[24, 25, 26, 27],
        [28, 29, 30, 31],
        [32, 33, 34, 35]],

       [[36, 37, 38, 39],
        [40, 41, 42, 43],
        [44, 45, 46, 47]],

       [[48, 49, 50, 51],
        [52, 53, 54, 55],
        [56, 57, 58, 59]]])

In [136]:
a2.ndim

3

In [137]:
a3=np.arange(56).reshape(7,4,2)
a3

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15]],

       [[16, 17],
        [18, 19],
        [20, 21],
        [22, 23]],

       [[24, 25],
        [26, 27],
        [28, 29],
        [30, 31]],

       [[32, 33],
        [34, 35],
        [36, 37],
        [38, 39]],

       [[40, 41],
        [42, 43],
        [44, 45],
        [46, 47]],

       [[48, 49],
        [50, 51],
        [52, 53],
        [54, 55]]])

In [139]:
a3.ndim

3

In [140]:
a3.shape

(7, 4, 2)

In [141]:
a3.size

56

In [142]:
a3.reshape(8,7)

array([[ 0,  1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12, 13],
       [14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39, 40, 41],
       [42, 43, 44, 45, 46, 47, 48],
       [49, 50, 51, 52, 53, 54, 55]])

# Numpy practice Session

In [55]:
#import Numpy library
import numpy as np

# Creating array using numpy

# 1-D array

In [58]:
food=np.array(["smosy","pakora","raita"])
food

array(['smosy', 'pakora', 'raita'], dtype='<U6')

In [57]:
price=np.array([5,5,5])
price

array([5, 5, 5])

In [59]:
type(food)

numpy.ndarray

In [60]:
type(price)

numpy.ndarray

In [61]:
len(food)

3

In [62]:
len(price)

3

In [64]:
price[2]

5

In [65]:
food[2]

'raita'

In [67]:
food[0:]

array(['smosy', 'pakora', 'raita'], dtype='<U6')

In [68]:
food[1]

'pakora'

In [69]:
price.mean()

5.0

In [70]:
#zeros method
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [71]:
#array of ones
np.ones(6)

array([1., 1., 1., 1., 1., 1.])

In [72]:
#empty arrays
np.empty(5)

array([1., 1., 1., 1., 1.])

In [76]:
#arange
np.arange(20)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [77]:
#range
np.arange(2,40)

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
       36, 37, 38, 39])

In [78]:
#write an array by starting from 2 and end on 40 but every digit should be with the interval of 5.
np.arange(2,40,5)

array([ 2,  7, 12, 17, 22, 27, 32, 37])

In [79]:
#table
np.arange(5,55,5)

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

In [80]:
# create an array with specific range but with specific number and interval. Lets have a look on example!
np.linspace(5, 200, num=50)
# example shows that make an array that start from 5 and stop at 200 and generate 50 digits of data. The interval should be same beween all numbers.

array([  5.        ,   8.97959184,  12.95918367,  16.93877551,
        20.91836735,  24.89795918,  28.87755102,  32.85714286,
        36.83673469,  40.81632653,  44.79591837,  48.7755102 ,
        52.75510204,  56.73469388,  60.71428571,  64.69387755,
        68.67346939,  72.65306122,  76.63265306,  80.6122449 ,
        84.59183673,  88.57142857,  92.55102041,  96.53061224,
       100.51020408, 104.48979592, 108.46938776, 112.44897959,
       116.42857143, 120.40816327, 124.3877551 , 128.36734694,
       132.34693878, 136.32653061, 140.30612245, 144.28571429,
       148.26530612, 152.24489796, 156.2244898 , 160.20408163,
       164.18367347, 168.16326531, 172.14285714, 176.12244898,
       180.10204082, 184.08163265, 188.06122449, 192.04081633,
       196.02040816, 200.        ])

In [81]:
# specify data type
np.ones(5,dtype=np.int64)

array([1, 1, 1, 1, 1])

In [82]:
np.ones(5,dtype=np.int16)

array([1, 1, 1, 1, 1], dtype=int16)

In [83]:
np.ones(5,dtype=np.int64)

array([1, 1, 1, 1, 1])

In [84]:
np.ones(5,dtype=np.int32)

array([1, 1, 1, 1, 1], dtype=int32)

In [85]:
np.ones(5,dtype=np.int64)

array([1, 1, 1, 1, 1])

In [86]:
np.ones(5,dtype=np.float16)

array([1., 1., 1., 1., 1.], dtype=float16)

In [87]:
np.ones(50,dtype=np.float64)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

# Array functions

In [89]:
a= np.array([10,12,15,20,30,100,320,10.30,400])
a

array([ 10. ,  12. ,  15. ,  20. ,  30. , 100. , 320. ,  10.3, 400. ])

In [92]:
a.sort()
a

array([ 10. ,  10.3,  12. ,  15. ,  20. ,  30. , 100. , 320. , 400. ])

In [93]:
b=np.array([2,4,5,6,7,2.10,3.20,400])
b

array([  2. ,   4. ,   5. ,   6. ,   7. ,   2.1,   3.2, 400. ])

In [94]:
c=np.concatenate((a,b))
c

array([ 10. ,  10.3,  12. ,  15. ,  20. ,  30. , 100. , 320. , 400. ,
         2. ,   4. ,   5. ,   6. ,   7. ,   2.1,   3.2, 400. ])

In [95]:
np.sort(c)

array([  2. ,   2.1,   3.2,   4. ,   5. ,   6. ,   7. ,  10. ,  10.3,
        12. ,  15. ,  20. ,  30. , 100. , 320. , 400. , 400. ])

# 2-D array

In [96]:
a=np.array([[2,3,5,2,4,7],[4,5,6,7,8,9]])
a

array([[2, 3, 5, 2, 4, 7],
       [4, 5, 6, 7, 8, 9]])

In [97]:
b=np.array([[6,7,4,3,2,5],[5,5,6,7,4,3]])
b

array([[6, 7, 4, 3, 2, 5],
       [5, 5, 6, 7, 4, 3]])

In [100]:
c=np.concatenate((a,b))
c

array([[2, 3, 5, 2, 4, 7],
       [4, 5, 6, 7, 8, 9],
       [6, 7, 4, 3, 2, 5],
       [5, 5, 6, 7, 4, 3]])

In [106]:
d=np.array([[6,8,7,4,7,6],[12,14,15,20,21,32],[12,14,15,20,21,32],[12,14,15,20,21,32]])
d

array([[ 6,  8,  7,  4,  7,  6],
       [12, 14, 15, 20, 21, 32],
       [12, 14, 15, 20, 21, 32],
       [12, 14, 15, 20, 21, 32]])

In [110]:
np.concatenate((c,d),axis=1)

array([[ 2,  3,  5,  2,  4,  7,  6,  8,  7,  4,  7,  6],
       [ 4,  5,  6,  7,  8,  9, 12, 14, 15, 20, 21, 32],
       [ 6,  7,  4,  3,  2,  5, 12, 14, 15, 20, 21, 32],
       [ 5,  5,  6,  7,  4,  3, 12, 14, 15, 20, 21, 32]])

In [111]:
np.concatenate((c,d),axis=0)

array([[ 2,  3,  5,  2,  4,  7],
       [ 4,  5,  6,  7,  8,  9],
       [ 6,  7,  4,  3,  2,  5],
       [ 5,  5,  6,  7,  4,  3],
       [ 6,  8,  7,  4,  7,  6],
       [12, 14, 15, 20, 21, 32],
       [12, 14, 15, 20, 21, 32],
       [12, 14, 15, 20, 21, 32]])

In [112]:
a=np.array([[ 2,  3,  5,  2,  4,  7],
       [ 4,  5,  6,  7,  8,  9],
       [ 6,  7,  4,  3,  2,  5],
       [ 5,  5,  6,  7,  4,  3],
       [ 6,  8,  7,  4,  7,  6],
       [12, 14, 15, 20, 21, 32],
       [12, 14, 15, 20, 21, 32],
       [12, 14, 15, 20, 21, 32]])
a

array([[ 2,  3,  5,  2,  4,  7],
       [ 4,  5,  6,  7,  8,  9],
       [ 6,  7,  4,  3,  2,  5],
       [ 5,  5,  6,  7,  4,  3],
       [ 6,  8,  7,  4,  7,  6],
       [12, 14, 15, 20, 21, 32],
       [12, 14, 15, 20, 21, 32],
       [12, 14, 15, 20, 21, 32]])

In [114]:
a.ndim

2

In [118]:
a=np.array([[2,3,4],[3,2,1]])
a

array([[2, 3, 4],
       [3, 2, 1]])

In [119]:
b=np.array([[4,2,1],[6,7,8]])
b

array([[4, 2, 1],
       [6, 7, 8]])

In [120]:
c=np.array([[8,9,0],[9,8,5]])
c

array([[8, 9, 0],
       [9, 8, 5]])

In [121]:
d=np.array([[1,0,9],[0,6,2]])
d

array([[1, 0, 9],
       [0, 6, 2]])

In [122]:
e=np.array([[1, 0, 9],
       [0, 6, 2],
           [8, 9, 0],
       [9, 8, 5],
           [4, 2, 1],
       [6, 7, 8]])
e

array([[1, 0, 9],
       [0, 6, 2],
       [8, 9, 0],
       [9, 8, 5],
       [4, 2, 1],
       [6, 7, 8]])

In [123]:
e.ndim

2

In [124]:
#how to check size of array (number of elements)
e.size

18

In [125]:
#shape of array


(6, 3)

In [133]:
ab1=np.array([[3,2,1],[1,2,3],[5,6,7]])
ab1

array([[3, 2, 1],
       [1, 2, 3],
       [5, 6, 7]])

In [134]:
ab1.ndim

2

# conversion of 1D array to 2D array

In [149]:
a4=np.array([3,4,5,6,7,8,9,4,1,2,12,20,22,40])
a4

array([ 3,  4,  5,  6,  7,  8,  9,  4,  1,  2, 12, 20, 22, 40])

In [150]:
a4.shape

(14,)

In [151]:
a4.size

14

In [154]:
a4.ndim

1

In [152]:
#row wise 2D conversion
a5=a4[np.newaxis, :]
a5

array([[ 3,  4,  5,  6,  7,  8,  9,  4,  1,  2, 12, 20, 22, 40]])

In [153]:
a5.ndim

2

In [ ]:
#columnwise wise 2D conversion

In [158]:
a6=a4[:,np.newaxis]
a6

array([[ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [ 4],
       [ 1],
       [ 2],
       [12],
       [20],
       [22],
       [40]])

In [159]:
x=np.arange(6)
x

array([0, 1, 2, 3, 4, 5])

In [160]:
#reshape rowwise
a2 = a[np.newaxis, :]
a2

array([[[2, 3, 4],
        [3, 2, 1]]])

In [161]:
a2.ndim

3

In [162]:
a2.shape

(1, 2, 3)

In [165]:
x2=a2[:,np.newaxis]
x2

array([[[[2, 3, 4],
         [3, 2, 1]]]])

In [167]:
x2=a2[:,np.newaxis]
x2

array([[[[2, 3, 4],
         [3, 2, 1]]]])